### ISSUE TITLE
Change tutorials to not overuse VectorDomain

### ISSUE THREAD

**Issue by andreasnoack** [PumasAI/PumasTutorials.jl#17]
I think it is generally easier to read the restrictions on the parameters when they are written as scalars such as https://github.com/UMCTM/PuMaS.jl/blob/1f83bebbf0348b432c1e051bb1e98127c7d227e2/test/nlme/theophylline.jl#L27-L30

compared using `VectorDomain`. Since `VectorDomain` doesn't allow for any joint properties anyway, I think we should consider simply specifying the θs element by element.

The `VectorDomain` struct also requires some infrastructure e.g. the `ElementArrayTransform` which could then also be removed but that is not the motivation here.

**Comment by pkofod** [comment]
Some of the turorials use vector domains others use realdomain now. That's maybe a good thing, such that users browsing the turorials will actually see the different types of domains in different tutorials. Or is the point of the issue to remove all vectordomain references?

**Comment by andreasnoack** [comment]
No. I've come more to terms with `VectorDomain` so let's just close this one. It's fine to have a mix.
