### ISSUE TITLE
unsatisfiable requirments detected for pkg pumas

### ISSUE THREAD

**Issue by Mutaz94** [PumasAI/PumasTutorials.jl#22]
when I try to install pumas package I get this alert. I tried more than one time
I use JuliaPro latest release

`using Pkg
Pkg.add("Pumas")
`
unsatisfiable requirments detected for pkg pumas

Thanks!

**Comment by ChrisRackauckas** [comment]
What is the error message it throws for that?

**Comment by Mutaz94** [comment]
I got this

Pumas [4f2c3c20] log:
 ├─possible versions are: [0.0.7, 0.1.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.7, 0.1.0]
 └─restricted by compatibility requirements with DiffEqDiffTools [01453d9d] to versions: uninstalled — no versions left
   └─DiffEqDiffTools [01453d9d] log:
     ├─possible versions are: [0.0.1-0.0.2, 0.1.0-0.1.2, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.1, 0.5.0, 0.6.0, 0.7.0-0.7.1, 0.8.0-0.8.1, 0.9.0, 0.10.0-0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.14.0] or uninstalled
     └─restricted to versions 0.10.1 by an explicit requirement, leaving only versions 0.10.1
in top-level scope at base\none
in add at stdlib\v1.1\Pkg\src\API.jl:64
in #add#22 at stdlib\v1.1\Pkg\src\API.jl:64 
in #add_or_develop at base\none 
in #add_or_develop#12 at stdlib\v1.1\Pkg\src\API.jl:33
in #add_or_develop at base\none 
in #add_or_develop#13 at stdlib\v1.1\Pkg\src\API.jl:34 
in #add_or_develop at base\none 
in #add_or_develop#16 at stdlib\v1.1\Pkg\src\API.jl:36 
in #add_or_develop at base\none 
in #add_or_develop#17 at stdlib\v1.1\Pkg\src\API.jl:59
in #add_or_develop at base\none 
in #add_or_develop#63 at stdlib\v1.1\Pkg\src\Operations.jl:1235
in resolve_versions! at stdlib\v1.1\Pkg\src\Operations.jl:328 
in resolve_versions! at stdlib\v1.1\Pkg\src\Operations.jl:388
in simplify_graph! at stdlib\v1.1\Pkg\src\GraphType.jl:1460 
in simplify_graph! at stdlib\v1.1\Pkg\src\GraphType.jl:1460 
in #simplify_graph!#121 at stdlib\v1.1\Pkg\src\GraphType.jl:1460
in propagate_constraints! at stdlib\v1.1\Pkg\src\GraphType.jl:946 
in #propagate_constraints!#61 at stdlib\v1.1\Pkg\src\GraphType.jl:1005

**Comment by vjd** [comment]
@Mutaz94 the download links were incorrect. We are correcting and updating them. Should be up and running Saturday evening EST. Will ping you here again

**Comment by andreasnoack** [comment]
What is the output from `Pkg.status()`?

**Comment by Mutaz94** [comment]
@andreasnoack 
it's even unresolved or undefined! 
@vjd Thanks

**Comment by andreasnoack** [comment]
Please paste the exact output here. (You'd have to do using Pkg; Pkg.status() if it's a new Julia session)

**Comment by Mutaz94** [comment]
Sure! 

    Status `C:\Users\mmthe\.juliapro\JuliaPro_v1.1.1.1\environments\v1.1\Project.toml`
  [c52e3926] Atom v0.8.5
  [a93c6f00] DataFrames v0.18.3
  [01453d9d] DiffEqDiffTools v0.10.1
  [7073ff75] IJulia v1.18.1
  [e5e0dc1b] Juno v0.7.0
  [d7b8c89e] PuMaS v0.0.6
  [b7b41870] PumasTutorials v0.0.1 #master (https://github.com/UMCTM/PumasTutorials.jl)
  [37e2e46d] LinearAlgebra

I think PuMaS Pkg is not the right one.

**Comment by vjd** [comment]
yup. This is an old one. you will get a new release by this evening or tomorrow morning!

**Comment by vjd** [comment]
@Mutaz94 -- I suggest that you uninstall your old JuliaPro, remove the `.juliapro` folder in your home folder. Then go to the downloads page and get a fresh install of JuliaPro. Follow the docs after installation. Basically `add Pumas` and you should be done!

**Comment by Mutaz94** [comment]
@vjd Thank you so much! Everything looks great now.
