### ISSUE TITLE
Review of tutorials for 1.0

### ISSUE THREAD

**Issue by andreasnoack** [PumasAI/PumasTutorials.jl#55]
- Introduction
  - [x] Introduction to Pumas (https://github.com/PumasAI/PumasTutorials.jl/pull/61)
  - [x] Generating and Simulating Populations (https://github.com/PumasAI/PumasTutorials.jl/pull/64)
  - [x] Introduction to Noncompartmental Analysis (NCA) (https://github.com/PumasAI/PumasTutorials.jl/pull/51 will replace this one)
- Workshop Materials
  - [x] Workshop Exercises
  - [x] Workshop Exercise Solutions
  - [x] Workshop Exercise Fitting
- Models
  - [x] Absorption models (https://github.com/PumasAI/PumasTutorials.jl/pull/67)
  - [x] Discrete Response Models (Fixed by https://github.com/PumasAI/PumasTutorials.jl/pull/44)
  - [ ] Indirect Response Models (Will get replaced by https://github.com/PumasAI/PumasTutorials.jl/pull/43)

**Comment by sipah00** [comment]
I'm working on updating code snippets in "Generating and Simulating Populations"

**Comment by andreasnoack** [comment]
I think that #56 has that one mostly covered

**Comment by sipah00** [comment]
Great, I didn't see this PR. I will close my pr.
