### ISSUE TITLE
can not install package Pipe

### ISSUE THREAD

**Issue by jp-julia** [PumasAI/PumasTutorials.jl#86]
Hi 
I get the following error when I install the package Pipe

importing Pipe into Main conflicts with an existing identifier
in include_string at base\loading.jl:1088

What can I do to install the package?

**Comment by vjd** [comment]
what version of Pumas are you on? If you download and use the latest release, 1.5.2-1, this problem should not exist. You can download from https://pumas.ai/products/pumas/download/

**Comment by jp-julia** [comment]
[cid:a69a1927-3b22-41ac-8565-0b335c66be8a]

Jaimini Patel
________________________________

**Comment by vjd** [comment]
what's the output of `julia> Pkg.status("Pumas")`

**Comment by jp-julia** [comment]
> what version of Pumas are you on? If you download and use the latest release, 1.5.2-1, this problem should not exist. You can download from https://pumas.ai/products/pumas/download/


I get an error: NSIS error  Installer integrity check has failed

**Comment by jp-julia** [comment]
ulia> Pkg.status("Pumas")
Status `C:\Users\starb\.julia\environments\JuliaPro_v1.5.0-2\Project.toml`
  [4f2c3c20] Pumas v1.0.3 ⚲


Jaimini Patel
________________________________

**Comment by vjd** [comment]
yeh, this issue is because of the previous version where we erroneously did not allow package updates. If you could update to the version on the website now, you should not face an issue.

**Comment by andreasnoack** [comment]
@jp-julia I've just succesfully installed the Windows binary from https://pumas.ai/products/pumas/download/ so could you please try to redownload the installler? The one you tried might have been corrupted during download.

**Comment by vjd** [comment]
@jp-julia  was able to download and install the new version and also add the Pipe package
